$include:
  - conf/vae/16khz-kl.yml

batch_size: 72
val_batch_size: 100
num_workers: 32
VAE.latent_dim: 8

amp: False


train/build_dataset.folders:
  speech:
    - /data/mazhengrui/dataset/LibriSpeech/train-other-500
    - /data/mazhengrui/dataset/LibriSpeech/train-clean-360
    - /data/mazhengrui/dataset/LibriSpeech/train-clean-100


val/build_dataset.folders:
  speech:
    - /data/mazhengrui/dataset/LibriSpeech/dev-clean

test/build_dataset.folders:
  speech:
    - /data/mazhengrui/dataset/LibriSpeech/test-clean